---
inherit_gem:
  kamaze-project:
    - .rubocop.yml
AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  SuggestExtensions: false
Style/RedundantException: { Enabled: false }
Style/TernaryParentheses: { Enabled: false }
