# frozen_string_literal: true

autoload(:Pathname, 'pathname')
require 'bundler/setup'
require 'aldine'
# load tasks --------------------------------------------------------
Pathname.new(Dir.pwd)
        .dirname
        .join('rake')
        .glob('/tasks/**/*.rb')
        .map(&:to_path)
        .sort
        .concat(['aldine/remote/tasks'])
        .each { |fp| require(fp) }
